content/about.md
- correct wiki URL in about page.
=> fix(about): Update old (sw360portal) WIKI URL to eclipse repository

content/presentations.md, content/resources.md
adding some more links to the resources page and adding a link to the presentation pages. also mainly in order to test the workflow.
=> feat(links): adding more links to resources and presentations

Jenkinsfile
Fix credentials ID and set HOME environment variable
Signed-off-by: Frederic Gurr <frederic.gurr@eclipse-foundation.org>
=> Bug 551892 - [CJE2JIRO] Migration of SW360 JIPP to Jiro

Jenkinsfile
Signed-off-by: Helio Chissini de Castro <heliocastro@gmail.com>
=> bug(jenkins): Fixed jenkins build

Jenkinsfile, content/en/_index.html, go.mod, go.sum
Signed-off-by: Helio Chissini de Castro <heliocastro@gmail.com>
=> bug(layout): Fix images loading

Jenkinsfile
=> fix(branch-name) : master to main

config.toml
Signed-off-by: Kouki Hama <kouki1.hama@toshiba.co.jp>
=> fix : Rename branch name in code master to main

content/en/docs/Deployment/Legacy/Native-Install-SW360-Version-14.0.0-and-16.0.0.md
Add how to configure portal-ext.properties and /etc/sw360/.
=> Fix the instructions for version 16.0.0 and rename

content/en/presentations/_index.md
Eclipse Conn and OSS summit Japan
=> Update presentation info

content/en/docs/Deployment/NativeInstall/_index.md
Signed-off-by: tuannn2 <tuan2.nguyennhu@toshiba.co.jp>
=> fix path folder Native Install

content/en/docs/Deployment/NativeInstall/Native-install-SW360-Version-17.0.0.md
- Update config log4j2 for native install sw360
=> fix(update): Update config log4j2 for native install sw360

content/en/docs/Development/TestCases/Test-Cases-Components.md
- Link a release to the project in view component page and check used by projects
- Link a release to a project in the view release page
- Import a new component by .spdx/.xml/ .rdf file
- Export components without releases
- Export components with releases
- Create a clearing request for a release
=> feat(docs): Add test case for component, release

content/en/docs/Development/TestCases/Test-Cases-Components.md
- Update outdated test cases for component and release
=> feat(docs): Update test case for Component, Release

content/en/docs/Deployment/NativeInstall/Native-install-SW360-Version-18.1.0.md
Add native install doc for 18.1.0 release
=> feat(Native install): Add native install doc for 18.1.0 release

content/en/docs/Development/TestCases/Test-Cases-Licenses.md
Update test cases for Licenses page.
=> Update test cases for Licenses.

content/en/docs/Deployment/BareMetal/Deploy-Natively.md
Change shell instructions to use ASCII quotes instead of MS Office.
=> fix(deploy): fix encoding for ASCII quotes

config.toml, content/en/gsoc/GSoC-projects-2025.md, content/en/gsoc/_index.md
1. Add pages for GSoC 2025 application
2. Fix link to repo
=> feat(gsoc): add pages for GSoC 2025 application

content/en/docs/Development/_index.md
fix : issue #67
Corrected spelling of where.
=> fix : issue #67

content/en/docs/Deployment/BareMetal/Deploy-19-Natively.md, content/en/docs/Deployment/Deploy-Configuration-Files.md
Add instructions to build and install new backend and frontend for version 19
=> feat(docs): build and install v19 backend and frontend

content/en/gsoc/GSoC-projects-2025.md, content/en/gsoc/_index.md
- Add Akshit Joshi as a mentor
- Change wording for GSoC 2025 participation
=> chore(gsoc): add akshit as mentor

content/en/gsoc/GSoC-projects-2025.md, content/en/gsoc/_index.md
Added my name as mentor for GSoc 2025.
=> feat(GSoc): Added my name as mentor

.github/workflows/build_and_publish.yml, config.toml, docker_serve_local.sh, go.mod, go.sum, package-lock.json, package.json
=> feat: Upgrade Hugo and Docsy to latest

assets/scss/_styles_project.scss, layouts/_default/baseof.html
=> feat: implement return to top arrow button

content/en/docs/Userguide/Components.md
fixes #52 
fix link for 1.05 Import SBOM and 1.13 Export Spreadsheet
=> fix: link for 1.05 Import SBOM and 1.13 Export Spreadsheet

content/en/docs/Development/Dev-External-Documents-with-CouchDB.md
**Descripition**:
-  Fixed for javascript loop typo.
-  Fixed Grammers
- Fixed Table inconsistency
cc: @KoukiHama @GMishx
=> feat(docs update): Improve CouchDB External Documents Handling

content/en/about/index.md, content/en/docs/_index.md
**Description:**
This PR enhances the About Eclipse SW360 documentation by improving clarity, consistency, and readability without altering functionality. It aligns with the broader SW360 Documentation & Website Improvement initiative, specifically under "Documentation Content Expansion & Optimization."
**Changes Made:**
- Improved grammar and sentence structure for better readability.
- Standardized bullet points and terminology for consistency.
- Fixed minor formatting issues to enhance the document's presentation.
- Refined ambiguous phrases to make the content clearer.
**Why this change?**
Improves user comprehension and experience.
Ensures consistency across the SW360 documentation.
Enhances professionalism and accessibility of the documentation.
Relevant Improvement Area:
✔ …
=> feat(doc update): Improve Readability and Consistency in SW360 About page

layouts/404.html
fixes #126 
@heliocastro @KoukiHama @GMishx please review this PR.
=> feat: Improve layout of 404 page

.github/workflows/dependabot.yml
Fix: #152 
This PR adds a `.github/dependabot.yml` file to enable automated dependency updates for the project.
Update schedule: **Weekly**
Why:
Keeping dependencies up to date improves project stability, security, and maintainability with minimal manual effort.
=> feat(add): Added Dependabot

CONTRIBUTING.md
- I have added this link to the contribution.md file because this file is important and useful for new upcoming contributors.
=> docs(add): added semantic commits link

layouts/partials/footer.html
- Updated the footer to ensure responsiveness across mobile, tablet, and desktop screens. 
- Demo:
https://github.com/user-attachments/assets/0646a25e-471b-444d-a664-f80ad1c317fb
=> fix(footer): Resposive Footer Layout

content/en/docs/Deployment/Deploy-Keycloak-Authentication.md
Add document how to change thrift backend url. Corresponding to PR https://github.com/eclipse-sw360/sw360/pull/3147
=> feat(keycloak): setup thrift location with spi config

.github/workflows/build_and_publish.yml, .github/workflows/commit_checks.yaml
Use GitHub actions to publish the website.
=> feat(cd): use GitHub actions to deploy website
